### ISSUE TITLE
TypeError: Cannot read property 'bundleIdentifier' of undefined

### ISSUE THREAD

**Issue by sjayendra** [vmurin/react-native-azure-auth-sample#5] opened 2021-01-28 17:48 UTC
Getting Above Error:
new Auth
node_modules/react-native-azure-auth/src/auth/index.js:32

  29 |  */
  30 | export default class Auth {
  31 |     constructor(options = {}) {
> 32 |         const bundleIdentifier = AzureAuth.bundleIdentifier
  33 |         const defaultRedirectUri = `${bundleIdentifier.toLowerCase()}://${bundleIdentifier.toLowerCase()}/${Platform.OS}/callback`
  34 | 

 
  29 | const { tenant = 'common', authorityUrl, clientId, redirectUri, persistentCache, ...extras } = options
  30 | 
> 31 | this.auth = new Auth({authorityUrl: (authorityUrl ? authorityUrl : `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/`),
     | ^  32 |     clientId,
  33 |     redirectUri,
  34 |     persistentCache,

**Comment by vmurin** [comment] 2021-01-28 19:58
AzureAuth is the native module. Most probable - you did not linked the module as described in the README.md
Try to link it and put some feedback here please :)

**Comment by sjayendra** [comment] 2021-01-29 02:58
Thanks for quick reply.  As per document I have made the following steps.
1. npm install react-native-azure-auth --save
2. npx react-native link

Am I missing any step ?   I am using Expo for initializing the project.

Regards,
Jayendra

**Comment by vmurin** [comment] 2021-01-29 08:05
Please consult the [issue #87](https://github.com/vmurin/react-native-azure-auth/issues/87) from the library repository.
So the solution for you would be to eject the app and if needed to use Expo Kit.

For now I will close the issue as duplicate of #87 mentioned above.

**Closed as completed by vmurin** 2021-01-29 08:05 UTC

**Comment by amf-paulo-airship** [comment] 2023-07-24 20:00
I am having the same error message however just on JEST. I am not using EXPO , I am using it on a React Native CLI Project. Anyone has any idea how to solve this ?
